### PR TITLE
Support gpl files

### PR DESCRIPTION
**Pull request by MathemanFlo**
Armorbase part of https://github.com/armory3d/armorpaint/pull/1357

### CODE REVIEW

**Comment by luboslenco** [comment]
Nice! Maybe we could do some general `isColorPalette`, even though only gpl is supported as of now?

**Comment by MathemanFlo** [comment]
I also thought about that. But for two reasons I did it differently
1. I needed a function to detect gpl files. I could have used endsWith directly but thought thise one is more elegant.
2. arm palettes (i.e. arm files that contain at least palettes) are not so easy to detect.

Please tell me what I should do and then I will change it or feel free to change it on your own if it is faster than explaining me.

**Comment by luboslenco** [comment]
> arm palettes (i.e. arm files that contain at least palettes) are not so easy to detect.

Hm true. Lets keep it as is then and get to it whenever we add more color palette formats.

**Comment by MathemanFlo** [comment]
> > arm palettes (i.e. arm files that contain at least palettes) are not so easy to detect.
> 
> Hm true. Lets keep it as is then and get to it whenever we add more color palette formats.

Okay. Good idea. In case you have a format in mind, feel free to let me know.

**Pull request merged**
